MODEL:
  TYPE: ada_swin
  NAME: swin_tiny_patch4_window7_224_tag
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    DECODER_DIM: 128

TRAIN:
    MTL_MULTI_OBJECTIVE_TRAIN: True
    EFFICIENCY_WEIGHT: 1.0
    TOKENS_EFFICIENCY_TARGET: 0.5
    BLOCKS_EFFICIENCY_TARGET: 0.9
    ADAPTIVE: True
    ADA_BLOCKS: True
    ADA_TOKENS: True
    HARD_GUMBEL: True
    LR_SCHEDULER:
      WARMUP_PREFIX: False
    POLICY: single
    TRAIN_MODE: default
    CONTROLLER_MODE: per_model
    BLOCK_CONTROLLER_DIM: 64
    TOKEN_CONTROLLER_DIM: 64
    WEIGHTED_TOKENS_LOSS: True
