MODEL:
  TYPE: ada_swin
  NAME: swin_small_patch4_window7_224_taw_pretrain
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7

TRAIN:
    CONTROLLERS_PRETRAIN: True
    ADA_BLOCKS: True
    ADA_TOKENS: True
    ADAPTIVE: False
    HARD_GUMBEL: False
    LR_SCHEDULER:
      WARMUP_PREFIX: False
    POLICY: per_task
    TASK_EPOCHS: 50
    TRAIN_MODE: default
    CONTROLLER_MODE: per_model
    BLOCK_CONTROLLER_DIM: 64
    TOKEN_CONTROLLER_DIM: 64
