MODEL:
  TYPE: ada_swin
  NAME: swin_small_patch4_window7_224_taw
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7

TRAIN:
    MTL_MULTI_OBJECTIVE_TRAIN: True
    ALTERNATING_TASK_TRAINING: True
    USE_SINGLE_TASK_LOSS: False
    COMBINED_FINE_TUNE: True
    EFFICIENCY_WEIGHT: 1.0
    TOKENS_EFFICIENCY_TARGET: 0.5
    BLOCKS_EFFICIENCY_TARGET: 0.9
    ADA_BLOCKS: True
    ADA_TOKENS: True
    ADAPTIVE: True
    HARD_GUMBEL: True
    LR_SCHEDULER:
      WARMUP_PREFIX: False
    POLICY: per_task
    TASK_EPOCHS: 100
    TRAIN_MODE: default
    CONTROLLER_MODE: per_model
    BLOCK_CONTROLLER_DIM: 64
    TOKEN_CONTROLLER_DIM: 64
    WEIGHTED_TOKENS_LOSS: True