DATA:
  # IMG_SIZE: [480, 640]
  # IMG_SIZE: [448, 448]
  IMG_SIZE: 224
MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_nyud
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 64
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    # NUM_HEADS: [ 2, 4, 8, 16 ]
    WINDOW_SIZE: 7

